### ISSUE TITLE
extension error when trying to install eslint

### ISSUE THREAD

**Issue by alvint** [brackets-userland/brackets-eslint#70]
I'm using Brackets 1.11 and if I try to install eslint I get an "Extension error" message. I tried a clean install of Brackets and installing node.js but that didn't help. If I leave the extension installed anyway and restart brackets, I get this error in the console:

```
ErrorNotification.js:122 [Extension] failed to load /Users/alvin/Library/Application Support/Brackets/extensions/user/zaggino.brackets-eslint - Error: Preference brackets-eslint.gutterMarks was redefined
```

**Comment by zaggino** [comment]
Brackets 1.11 includes this extension by default. You can try uninstalling the one in your user extensions.

**Comment by alvint** [comment]
Cool! I was wondering why the "zaggino" prefix was removed in the preferences.
